gui:
  showIcons: true
  nerdFontsVersion: "3"
  theme:
    # Border color of focused window
    activeBorderColor:
      - '#d79922'
      - bold
    # Border color of non-focused windows
    inactiveBorderColor:
      - '#269bb2'
    # Border color of focused window when searching in that window
    searchingActiveBorderColor:
      - '#d79922'
      - bold
    # Background color of selected line.
    # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#highlighting-the-selected-line
    selectedLineBgColor:
      - '#283457'
